name: release

on:
  workflow_dispatch:
  
  push:
    branches: [ main, next ]
    paths-ignore:
      - '**.md'

env:
  node: 15
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:

  task:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ lint, build, test ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - run: npm ci
      - run: npm run ${{ matrix.task }}

  release:
    runs-on: ubuntu-latest
    needs: task
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-
      - run: npm ci
      - run: npm run build
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
